%GEAR-SCouP Program by NREL GRC-GEARTECH
%Yi Guo
%NREL NWTC
%12/06/2013
%
%This program evaluates spline coupling design spline coupling rating
%analysis. 
%The model is from "Gearbox Reliability Collaborative: An
%Analytic Formulation for the Evaluation of Spline Couplings".


function GearCoupling_GRC_GUI_NETABLE
clc
% clear all;
close all;
global results
global parameters parameters_data
global data_summary
global FileStats
global file_time
global file_size
global names
global DIREC
global event_boundary
global val
global leg
global location
global filename
global path
global channels
global iteration
global load_names
global times
global datevnt
global header
global single %boolean: if analysis is based on single file
global th_1;
global th_2;
global th_3;
global tbl;
global unit_channels unit_iteration unit_load;
global fid ax;

opengl software;
single=0;
%check variables
% whos
% keyboard
% Creating the Figures
% Main figure
fh = figure('MenuBar','none','Name','Gear Coupling Program',...
    'NumberTitle','off','Visible','off',...
    'Position',[20 20 1800 1000],'Color',[0.9 0.91 0.91],...
    'Toolbar','figure');

% Adding the Buttons & Graphs
% Menu - lets the user select which way to get data

okh = uicontrol(fh,'Style','pushbutton','String','Load Input File',...
    'Position',[50 920 200 35],'Visible','on',...
    'FontSize',10,'FontWeight','bold');
seh = uicontrol(fh,'Style','pushbutton','String','Review/Edit Input Parameters',...
    'Position',[50 860 200 35],'Visible','on',...
    'FontSize',10,'FontWeight','bold');

prh = uicontrol(fh,'Style','pushbutton','String',...
    'Start Analysis >>',...
    'Position',[50 800 200 35],'Visible','on',...
    'FontSize',10,'FontWeight','bold');
% Export Button - proceed to export gui
rrh = uicontrol(fh,'Style','pushbutton','String',...
    'Result Review >>',...
    'Position',[50 740 150 35],'Visible','on',...
    'FontSize',10,'FontWeight','bold');

% Export Button - proceed to export gui
erh = uicontrol(fh,'Style','pushbutton','String',...
    'Save Result >>',...
    'Position',[50 580 150 35],'Visible','on',...
    'FontSize',10,'FontWeight','bold');

eprh = uicontrol(fh,'Style','pushbutton','String',...
    'Capture Image >>',...
    'Position',[50 520 150 35],'Visible','on',...
    'FontSize',10,'FontWeight','bold');

ekh = uicontrol(fh,'Style','pushbutton','String','Exit',...
    'Position',[1700 40 50 30],'Visible','on',...
    'FontSize',10,'FontWeight','bold');


% Help button - Brings up the help menu
hmh = uicontrol(fh,'Style','pushbutton','String','Help',...
    'Position',[1700 900 50 30],'Visible','on',...
    'FontSize',8,'FontWeight','bold');

% Checkboxes - select what to plot / what is currently displayed in plot
cbh1 = uicontrol(fh,'Style','checkbox','String','Bending/Contact/Yield Stress',...
    'Position',[60 710 230 20],'Visible','on',...
    'BackGroundColor',[0.7 1 1],'FontSize',10,'Value',1);

cbh2 = uicontrol(fh,'Style','checkbox','String','Coupling strength',...
    'Position',[60 690 230 20],'Visible','on',...
    'BackGroundColor',[0.7 1 1],'FontSize',10);
cbh3 = uicontrol(fh,'Style','checkbox','String','Safety factor',...
    'Position',[60 670 230 20],'Visible','on',...
    'BackGroundColor',[0.7 1 1],'FontSize',10);
cbh4 = uicontrol(fh,'Style','checkbox','String','Tooth Contact Pattern',...
    'Position',[60 650 230 20],'Visible','on',...
    'BackGroundColor',[0.7 1 1],'FontSize',10);

ax = axes('unit','pixels','Position',[30 20 1700 950]);
set(ax,'visible','on','Box','on','XTick',[], 'YTick',[]);
title(ax,['Gear Coupling Program, GearTech/NREL'],'fontsize',10,'FontWeight','bold');
text(0,40,ax,'Gear Coupling Program, GearTech/NREL','fontsize',10,'FontWeight','bold');

nrel = imread('nrel_logo.jpg');
lh = axes('unit','pixels','Position',[50 50 170 125]);

hi = imagesc(nrel);
set(lh,'handlevisibility','off', ...
    'visible','off')


gt = imread('geartechlogo.jpg');
lh = axes('unit','pixels','Position',[50 180 160 28]);
hi = imagesc(gt);
set(lh,'handlevisibility','off', ...
    'visible','off')


fid = fopen('log.txt','w');


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
cell_data = {...
    'Number of teeth','';...
    'Diametral pitch','';...
    'Effective face width, 1/inch','';...
    'Distance between gear mesh centerline, inch','';...
    'Pressure angle, degree','';...
    'Design mislignment angle, degree','';...
    'Hub tooth circular tooth thickness, inch','';...
    'Sleeve circular tooth thickness, inch','';...
    'Major diameter of hub, inch','';...
    'Minor diameter of sleeve, inch','';...
    'Hub tooth tip chamfer, inch','';...
    'Face crown radius, normal, inch','';...
    'Face crown height, inch','';...
    'Root crown radius at pitch diameter, inch','';...
    'Hob tooth AGMA form factor','';...
    'Sleeve tooth AGMA form factor','';...
    'Hub tooth stress concentration factor','';...
    'Accuracy factor','';...
    'Young modulus, psi','';...
    'Rated Torque, in-lbf','';...
    'Heat Treatment','';...
    'Type A/B, Induction-Hardened','';...
    'HB, Through-Hardened','';...
    'Su, Case tensile strength, ksi','';...
    'Su, Core tensile strength, ksi','';...
    'Sy, Case yield strength, ksi','';...
    'Su, Core yield strength, ksi','';...
    'Integration tolerance','';...
    'Minimum misalignment angle,degree','';...
    'Maximum misalignment angle, degree','';...
    'Angle increase step, degree','';...
    'Ratio between minimum torque and rated','';...
    'Ratio between maximum torque and rated','';...
    'Torque increase step','';...
    };
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
columneditable =  [true];
rnames = {'Value'};

% Setting Callbacks for buttons
% Assign functions to the buttons so when they are pushed something happens
set(okh,'Callback',{@getdata_callback,fh,ax,[cbh1;cbh2;cbh3;cbh4]...
    },'BusyAction','Cancel');
set(prh,'Callback',{@compute_callback,fh,ax,[cbh1;cbh2;cbh3;cbh4]});
set(seh,'Callback',{@review_callback,fh,ax,[cbh1;cbh2;cbh3;cbh4]});
set(rrh,'Callback',{@export_callback,fh,ax,[cbh1;cbh2;cbh3;cbh4]});
set(erh,'Callback',{@savedata_callback,fh,ax});
set(eprh,'Callback',{@saveplot_callback,fh,ax});
% Checkboxes
set(cbh1,'Callback',{@checkbox_callback,ax,[cbh1;cbh2;cbh3;cbh4]},...
    'BusyAction','cancel');
set(cbh2,'Callback',{@checkbox_callback,ax,[cbh1;cbh2;cbh3;cbh4]},...
    'BusyAction','cancel');
set(cbh3,'Callback',{@checkbox_callback,ax,[cbh1;cbh2;cbh3;cbh4]},...
    'BusyAction','cancel');
set(cbh4,'Callback',{@checkbox_callback,ax,[cbh1;cbh2;cbh3;cbh4]},...
    'BusyAction','cancel');

set(hmh,'Callback',{@help_callback},'BusyAction','cancel');
set(ekh,'Callback',{@exit_callback,fh},'BusyAction','cancel');

% Make the figure visible
set(fh,'Visible','on');

% Shutoff unnecessary warnings

warning off MATLAB:xlswrite:AddSheet

% Give the buttons functionality.
    function getdata_callback(hObject,eventdata,fh,ax,cbh,tbl)
        
        %                 text(0.5,0.5,'Starting to acquire data...');
        if isempty(ax)
        else
            ax = axes('unit','pixels','Position',[300 20 1500 950]);
            set(ax,'visible','on','Box','on','XTick',[], 'YTick',[]);
        end
        %
        pause(.1)
        event_boundary = [];    % Reset global variables so user can switch
        FileStats =[];          % between DIRECtories quickly
        datevnt = [];
        times = [];
        
        single=1;
        % Single File
        %         Get values from checkboxes for plotting
        chval = get(cbh,'Value');
        val = cell2mat(chval);
        
        %         Get a single file.
        [fname,DIREC,filterindex] = uigetfile({'*.txt'});
        
        fullname = fullfile(DIREC,fname);
        %         get date and sample rate from file name
        parameters=importdata(fullname);
        channels={'Number of teeth',...
            'Diametral pitch',...
            'Effective face width, 1/inch',...
            'Distance between gear mesh centerline, inch',...
            'Pressure angle, degree',...
            'Design mislignment angle, degree',...
            'Hub tooth circular tooth thickness, inch',...
            'Major diameter of hub, inch',...
            'Minor diameter of sleeve, inch',...
            'Hub tooth tip chamfer, inch',...
            'Sleeve circular tooth thickness, inch',...
            'Face crown radius (normal), inch',...
            'Face crown height, inch',...
            'Root crown radius at pitch diameter, inch',...
            'Hob tooth AGMA form factor',...
            'Sleeve tooth AGMA form factor',...
            'Hub tooth stress concentration factor',...
            'Accuracy factor',...
            'Young modulus, psi',...
            'Rated Torque, in-lbf',...
            'Heat Treatment',...
            'Type A/B, Induction-Hardened',...
            'HB, Through-Hardened',...
            'Su, Case tensile strength, ksi',...
            'Su, Core tensile strength, ksi',...
            'Sy, Case yield strength, ksi',...
            'Su, Core yield strength, ksi'
            };
        unit_channels={'N/A';'1/inch';'inch';'inch';...
            'degree';'degree';'inch';'inch';...
            'inch';'inch';'inch';'inch';'inch';'N/A';...
            'N/A';'N/A';'N/A';'';...
            'in-lbf';'HB';'?';'inch'};
        iteration={'Integration tolerance'};
        unit_iteration={'inch'};
        load_names={'Minimum misalignment angle, degree',...
            'Maximum misalignment angle, degree',...
            'Angle increase step, degree',...
            'Ratio between minimum torque and rated',...
            'Ratio between maximum torque and rated',...
            'Torque increase step'};
        unit_load={'degree';'degree';'degree';'N/A';'N/A';'N/A'};
        names = dir(fullfile(DIREC,fname));
        
        
        clear text; text(0.025,0.5,ax,'Input Parameter Loaded!','fontsize',10,'FontWeight','bold', 'HorizontalAlignment','left',...
            'BackgroundColor',[.7 .9 .7]);
        a_str='Input file loaded.';
        fprintf(fid, '%s\r\n', a_str);
        
    end
%dat = rand(3);

    function  review_callback(hObject,eventdata,fh,ax,cbh,tbl)
        
        if isempty(ax)
        else
            ax = axes('unit','pixels','Position',[300 20 1700 950]);
            set(ax,'visible','on','Box','on','XTick',[], 'YTick',[]);
        end
        %
        %
        %         %%%%%%%%%%%%%%
        fig = fh;
        
        
        dat =parameters;
        if isempty(dat)
            cell_data = {...
                'Number of teeth','';...
                'Diametral pitch','';...
                'Effective face width, 1/inch','';...
                'Distance between gear mesh centerline, inch','';...
                'Pressure angle, degree','';...
                'Design mislignment angle, degree','';...
                'Hub tooth circular tooth thickness, inch','';...
                'Major diameter of hub, inch','';...
                'Minor diameter of sleeve, inch','';...
                'Hub tooth tip chamfer, inch','';...
                'Face crown radius, normal, inch','';...
                'Face crown height, inch','';...
                'Root crown radius at pitch diameter, inch','';...
                'Hob tooth AGMA form factor','';...
                'Sleeve tooth AGMA form factor','';...
                'Hub tooth stress concentration factor','';...
                'Sleeve circular tooth thickness, inch','';...
                'Accuracy factor','';...
                'Young modulus, psi','';...
                'Rated Torque, in-lbf','';...
                'Heat Treatment','';...
                'Type A/B, Induction-Hardened','';...
                'HB, Through-Hardened','';...
                'Su, Case tensile strength, ksi','';...
                'Su, Core tensile strength, ksi','';...
                'Sy, Case yield strength, ksi','';...
                'Su, Core yield strength, ksi','';...
                'Integration tolerance','';...
                'Minimum misalignment angle,degree','';...
                'Maximum misalignment angle, degree','';...
                'Angle increase step, degree','';...
                'Ratio between minimum torque and rated','';...
                'Ratio between maximum torque and rated','';...
                'Torque increase step','';...
                };
        else
            cell_data = {...
                'Number of teeth',dat(1);...
                'Diametral pitch',dat(2);...
                'Effective face width, 1/in',dat(3);...
                'Distance between mesh, in',dat(4);...
                'Pressure angle, degree',dat(5);...
                'Design mislignment, degree',dat(6);...
                'Hub tooth thickness, inch',dat(7);...
                'Major diameter, hub, inch',dat(8);...
                'Minor diameter,sleeve, inch',dat(9);...
                'Hub  tip chamfer, inch',dat(10);...
                'Face crown radius, normal, inch',dat(11);...
                'Face crown height, inch',dat(12);...
                'Root crown radius at pitch, inch',dat(13);...
                'Hob tooth AGMA form factor',dat(14);...
                'Sleeve tooth AGMA form factor',dat(15);...
                'Hub stress concentration factor',dat(16);...
                'Sleeve tooth thickness, inch',dat(17);...
                'Accuracy factor',dat(18);...
                'Young modulus, psi',dat(19);...
                'Rated Torque, in-lbf',dat(20);...
                'Heat Treatment',dat(21);...
                'Type A/B, Induction-Hardened',dat(22);...
                'HB, Through-Hardened',dat(23);...
                'Su, Case tensile strength, ksi',dat(24);...
                'Su, Core tensile strength, ksi',dat(25);...
                'Sy, Case yield strength, ksi',dat(26);...
                'Su, Core yield strength, ksi',dat(27);...
                'Integration tolerance',dat(28);...
                'Minimum misalignment,degree',dat(29);...
                'Maximum misalignment, degree',dat(30);...
                'Angle increase step, degree',dat(31);...
                'Minimum torque/rated',dat(32);...
                'Maximum torque/rated',dat(33);...
                'Torque increase step',dat(34);...
                };
        end
        
        
        columninfo.titles={'Param','value'};
        columninfo.formats = {'%4.6g','%4.6g'};
        columninfo.weight = [ 1, 1];
        columninfo.multipliers = [ 1, 1 ];
        columninfo.isEditable = [ 1, 1];
        columninfo.isNumeric = [ 0, 1];
        columninfo.withCheck = true;
        columninfo.chkLabel = 'Use';
        rowHeight = 16;
        gFont.size=10;
        gFont.name='Helvetica';
        
        columneditable =  [true];
        rnames = {'Value'};
        
        %
        columnformat = {'char', 'numeric'};
        tbl = uitable('Parent',fh,'Data',dat(1:34),'ColumnName',rnames ,'ColumnEditable', columneditable,'ColumnWidth',{100 100},...
            'RowName',cell_data(1:34),'Position',[20 50 525 400], 'ColumnFormat', columnformat);
        
        
        a_str='Review data.';
        fprintf(fid, '%s\r\n', a_str);
        
        
        
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        
        
        
        disp(tbl)
    end

% Select Events
    function compute_callback(hObject,eventdata,fh,ax,cbh,tbl)
        
        disp('start analysis')
        
        %         if isempty(tbl)
        %         else
        %             set(tbl,'visible','off');
        %         end
        %         if isempty(ax)
        %         else
        ax = axes('unit','pixels','Position',[300 20 1700 950]);
        set(ax,'visible','on','Box','on','XTick',[], 'YTick',[]);
        %         end
        %         if isempty(tbl)
        %         else
        %             info = get(tbl,'UserData');
        %             parameters = cell2mat(info.data(:,2));
        %             disp(parameters);
        %         end                % add back on when table is editable
        
        [results]=GearCoupling_compute(parameters);
        text(0.025,0.45,ax,'Analysis Done!','fontsize',10,'FontWeight','bold', 'HorizontalAlignment','left',...
            'BackgroundColor',[.7 .9 .7]);
        a_str='Compute data completed.';
        fprintf(fid, '%s\r\n', a_str);
        
    end

%  Plot Events
    function export_callback(hObject,eventdata,fh,ax,cbh,tbl)
        
        if isempty(ax)
        else
            ax = axes('unit','pixels','Position',[300 20 1700 950]);
            set(ax,'visible','on','Box','on','XTick',[], 'YTick',[]);
        end
        %                 if isempty(tbl)
        %                 else
        %                 set(tbl,'Visible','off');
        %                 end
        
        Ie=results.Ie;
        z0=results.z0;
        z9=results.z9;
        q=results.q;
        W1=results.W1;
        W2=results.W2;
        W3=results.W3;
        S1=results.S1;
        S2=results.S2;
        S3=results.S3;
        n_bf=results.n_bf;
        n_cf=results.n_cf;
        n_sf=results.n_sf;
        n_by=results.n_sf;
        n_cy=results.n_cy;
        n_sy=results.n_sy;
        S_bending=results.S_bending;
        S_contact=results.S_contact;
        S_shear=results.S_shear;
        PHI=results.PHI;
        PHI=results.PHI;
        I_max=results.I_max; % Maximm tilting angle before jamming
        I_var=results.I_var;
        Torque_var=results.Torque_var;
        len_I=length(I_var);
        len_torque=length(Torque_var);
        
        if (len_I==1 && len_torque==1)
            if I_var==0
                table_data=[Torque_var,I_var,Ie, z0,z9,q,W1,W2,S1,S2,S3,n_bf,n_cf,n_sf,n_by,n_cy,n_sy,S_bending,S_contact,S_shear,I_max];
            else
                table_data=[Torque_var,I_var,Ie, z0,z9,q,W1,W3,S1,S2,S3,n_bf,n_cf,n_sf,n_by,n_cy,n_sy,S_bending,S_contact,S_shear,I_max];
            end
            DataNames = {'Torque, in-lb',...
                'Misalignment, degree',...
                'Equivalent Parallel Offset, in',...
                'Maximum Tooth Separation, in',...
                'Tooth Deformation Ratio',...
                'Load Sharing Factor',...
                'Total Tangential Load, lb',...
                'Max Tooth Load, lb',...
                'Bending Stress, psi',...
                'Hertizian Stress, psi',...
                'Shear Stress, psi',...
                'Safety factor, bending, fatigue',...
                'Safety factor, contact, fatigue',...
                'Safety factor, shear, fatigue',...
                'Safety factor, bending, yield',...
                'Safety factor, contact, yield',...
                'Safety factor, shear, fatigue',...
                'Strength_bending,psi',...
                'Strength_contact,psi',...
                'Strength_shear, psi',...
                'I_max, degree'};
            rnames = {'Value'};
            columneditable =  [true];
            rnames = {'Value'};
            %     th_1 =
            columnformat = {'char', 'numeric'};
            tbl=uitable('Parent',fh,'Data',table_data','ColumnName',rnames ,'ColumnEditable', columneditable,'ColumnWidth',{100,100},...
                'RowName',DataNames,'Position',[20 50 525 400], 'ColumnFormat', columnformat);
            %             set(tbl(end),'Enable','on');
            plots(val,parameters,results,fh,ax,th_1);
        else
            plots(val,parameters,results,fh,ax,th_1);
        end
    end

%%% Save Data Function
    function savedata_callback(hObject,eventdata,fh,ax,tbl)
        
        %                  title(ax,'Writing results.....!');
        text(-7,16,ax,'Writing results.....!','fontsize',10,'FontWeight','bold', 'HorizontalAlignment','left',...
            'BackgroundColor',[.7 .9 .7]);
        pause(.1);
        name='output.xlsx';
        delete('output.xlsx');
        
        if ~isempty(who('results','global'))
            VarList ={'Ie',...
                'z0',...
                'z9',...
                'q',...
                'W1',...
                'W2',...
                'W3',...
                'S1',...
                'S2',...
                'S3',...
                'n_bf',...
                'n_cf',...
                'n_sf',...
                'n_by',...
                'n_cy',...
                'n_sy',...
                'S_bending',...
                'S_contact',...
                'S_shear',...
                'I_max',...
                'I_var',...
                'Torque_var'};
            VarNames = {'Equivalent Parallel Offset, in',...
                'Maximum Tooth Separation, in',...
                'Tooth Deformation Ratio',...
                'Load Sharing Factor',...
                'Total Tangential Load, lb',...
                'W2',...
                'Max Tooth Load, lb',...
                'Bending Stress, psi',...
                'Hertizian Stress, psi',...
                'Shear Stress, psi',...
                'Safety factor, bending, fatigue',...
                'Safety factor, contact, fatigue',...
                'Safety factor, shear, fatigue',...
                'Safety factor, bending, yield',...
                'Safety factor, contact, yield',...
                'Safety factor, shear, fatigue',...
                'Strength_bending,psi',...
                'Strength_contact,psi',...
                'Strength_shear, psi',...
                'I_max, radian',...
                'I_var, radian',...
                'Torque_var, in-lb'};
            
            for vi = 1:numel(VarList)
                if vi<17
                    xlswrite(name,results.Torque_var,VarNames{vi},['B1'])
                    xlswrite(name,results.I_var',VarNames{vi},['A2'])
                else
                end
                xlswrite(name,results.(VarList{vi}),VarNames{vi},['B2'])
            end
            
            
        end
        text(-8.5,14,ax,'Results saved!','fontsize',10,'FontWeight','bold', 'HorizontalAlignment','left',...
            'BackgroundColor',[.7 .9 .7]);
        a_str='Data saved.';
        fprintf(fid, '%s\r\n', a_str);
    end

    function saveplot_callback(hObject,eventdata,fh,ax,tbl)
        
        text(-7.5,15,ax,'Writing results.....!','fontsize',10,'FontWeight','bold', 'HorizontalAlignment','left',...
            'BackgroundColor',[.7 .9 .7]);
        %         hgsave to save individual figures.!!
        pause(.1);
        if ~isempty(who('results','global'))
            fr = getframe(fh);
            [x,m] = frame2im(fr);
            imwrite(x,fullfile(path,[filename(1:end-4) 'Waterfall.jpg']));
            
            text(-7.5,15,ax,'Image saved!!','fontsize',10,'FontWeight','bold', 'HorizontalAlignment','left',...
                'BackgroundColor',[.7 .9 .7]);
        end
        a_str='Image saved.';
        fprintf(fid, '%s\r\n', a_str);
    end



    function checkbox_callback(hObject,eventdata,ax,cbh)
        if ~isempty(results)
            %                         Find which checkboxes are activated
            val = get(cbh,'Value');
            val = cell2mat(val);
            
        end
    end

    function help_callback(hObject,eventdata)
        hfh = figure('MenuBar','none','Name','Help on running GEAR-SCouP',...
            'NumberTitle','off','Visible','off',...
            'Position',[360 502 560 420],'Color',[1 1 1]);
        annotation('textbox',[30/560 30/420 500/560 360/420],'String',...
            ['To Run GEAR-SCouP -> Run-GRCGEARSCouP.exe -> Load input file *.txt -> Review input parameter -> Start analysis -> Result review -> Save result -> Exit       '...
            %             'Load input File type -> .txt file currently.'...
            % 'Review Input Parameters-> review the parameter before run analysis. Editing functionality is disabled for now as there is compatibility issue with Matlab MCR.',...
            % 'Start Analysis-> compute stress/strength/safety factor programs.'
            % 'Result review-> this button prompts the plots. The check box below is user-selected output to be shown in the screen.'...
            % 'Save results-> export all the results to a spreadsheet in the same working folder “data.xls”'...
            % 'Capture image-> save images to .jpg files'...
            % 'Exit-> exit the program' ...
            ],...
            'FontSize',12);
        
        okh = uicontrol(hfh,'Style','pushbutton','String','OK',...
            'Position',[265 5 30 20],'Visible','on',...
            'FontSize',8,'FontWeight','bold');
        
        set(okh,'Callback',{@okay_callback,hfh});
        
        set(hfh,'Visible','on');
        
        function okay_callback(hObject,eventdata,hfh)
            close(hfh);
        end
    end

    function exit_callback(hObject,eventdata,hfh)
        close(hfh);
        close all;
        fclose(fid);
    end

end
